apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  labels:
    app: { { .Values.service.label } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
  selector:
    app: { { .Values.service.label } }
