apiVersion: v1
kind: Service
metadata:
  name: sftpgo-service
  labels:
    app: sftpgo
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: sftpgo
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: sftp
      protocol: TCP
      port: 2022
      targetPort: 2022
