apiVersion: v1
kind: Service
metadata:
  name: sftpgo-service
  labels:
    app: sftpgo
spec:
  type: LoadBalancer
  ports:
    - port: 2022
      targetPort: 2022
      protocol: TCP
      name: sftp
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sftpgo
